### ISSUE TITLE
richcompare functions could use a once-over.

### ISSUE THREAD

**Issue by melzaren** [LimpingNinja/nakedmud#3]
grep "richcompare" in the scripts directory will show you some compare functions.

As I coded them out of necessity as a port to 3.11 I did them on the fly. Maybe a second eye would be helpful to ensure it's all correct/optimal.

**Comment by LimpingNinja** [comment]
I just checked richcompare on the Accounts and overall it looks perfectly fine. From a coding perspective, you could simplify a few of the calls, but it's nothing major and doesn't cause too much impact. 

```c
    // Cast the objects to PyAccount type
    PyAccount *acc1 = (PyAccount *)obj1;
    PyAccount *acc2 = (PyAccount *)obj2;

    // Compare the account names case-insensitively
    int retval = !strcasecmp(accountGetName(acc1->account), accountGetName(acc2->account));

    // Invert the result for inequality comparison
    if (op == Py_NE) {
        retval = !retval;  // Simpler way to invert the result
    }

    // Return True or False based on the comparison result
    return retval ? Py_True : Py_False;
```
